name: Check
on: push
jobs:
  debug:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v3
      - name: Compilation
        run: "scripts/ci/build.sh"
      - name: Check Multiboot2 for x86
        # TODO support multiple architectures
        run: "grub-file --is-x86-multiboot2 target/x86/debug/maestro"
  release:
    runs-on: [ self-hosted, linux ]
    needs: debug
    steps:
      - uses: actions/checkout@v3
      - name: Compilation
        run: "CARGOFLAGS='--release' scripts/ci/build.sh"
      - name: Check Multiboot2 for x86
        # TODO support multiple architectures
        run: "grub-file --is-x86-multiboot2 target/x86/release/maestro"
  selftest:
    runs-on: [ self-hosted, linux ]
    needs: debug
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: "scripts/ci/selftest.sh"
  strace:
    runs-on: [ self-hosted, linux ]
    needs: debug
    steps:
      - uses: actions/checkout@v3
      - name: Compilation
        run: "CARGOFLAGS='--features strace' scripts/ci/build.sh"
      - name: Check Multiboot2 for x86
        # TODO support multiple architectures
        run: "grub-file --is-x86-multiboot2 target/x86/debug/maestro"
  format:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --check
  documentation:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v3
      - name: Build book
        run: "mdbook build doc/"
      - name: Build references
        run: "scripts/ci/doc.sh"
